### ISSUE TITLE
Enable software flow control in Ninja scan light sensor

### ISSUE THREAD

**Issue by shourie5794** [fenrir-naru/ninja-scan-light#11]
Hello,
I am using Ninja Scan device with imx6 board.
In my application when i do byte read,some of the bytes are lost .
I had tried this with different baud rate, but issue still exists.
I want to  know how to enable software flow control of ninja scan device.

I found similar issue discused in below link : 
https://github.com/fenrir-naru/ninja-scan-light/issues/10
Thank you

**Comment by fenrir-naru** [comment]
Thank you for your comment.
please see #10 .

**Comment by fenrir-naru** [comment]
In addition, the baudrate setting is meaningless (dummy), because the USB-CDC implementation does not provide baudrate emulation.
