### ISSUE TITLE
can't get NAV-POSLLH data by Changing telemetry config.

### ISSUE THREAD

**Issue by takespace** [fenrir-naru/ninja-scan-light#14]
Can't get NAV-POSLLH data.
I used v1.1.2.

I changed telemetry config by using "renew_cfg_gen.rb".

Before:
148        [0x01, 0x06, 5], # NAV-SOL: approximately 1 Hz]

After:
148        [0x01, 0x02, 5], # NAV-SOL: approximately 1 Hz]

Then, I got strange data below.
B5 62 1 2 1C 0 B5 62 1 2 1C 0 B5 62 1 2 1C 0 B5 62 1 2 1C 0 B5 62 1 2 1C 0 B5 62 1 2 1C 0

Every 5 times this data will repeat, after that UBX streaming will stop for about 3sec.
data logger repeat this sequence.

Data in SD card has no problem.

Now I'm reading gps.c but I can't solve yet....

**Comment by fenrir-naru** [comment]
Thank you for informing me another problem.
I reproduced the problem in my environment.
The problem was related to the mechanism of packet type recognition and I found and fixed the bug with a67afe1908cb50e826e4f4cfde1052fa552c4080 .
Please check it.
