### ISSUE TITLE
Interpretation and meanings of sensor values

### ISSUE THREAD

**Issue by pitaslayer** [fenrir-naru/ninja-scan-light#15]
Hello!

I'm using your "sensor board" to try out my first experiences in the hardware / sensor kind of stuff. The board works greatly and the data frequency of it is perfect for my experiences. However, I cant figured out how to translate the values from the dump file to "normal" values. For example my temperature value is 28304 and I know that the value isnt in Celsius or Fahrenheit. How can I convert to that?

Kind Regards,
T

**Comment by fenrir-naru** [comment]
Hi,
Did you see [the format page in Wiki](https://github.com/fenrir-naru/ninja-scan-light/wiki/LogFile)? If you need further information, you can find it in the data sheet of the sensors.
Or, you can use the latest log_CSV binary (downloadable from Files section on [Bintray](https://bintray.com/fenrir-naru/github/ninja-scan-light/_latestVersion)), which is the standard converter of generated log.dat, with "--physical" option. Some raw values are converted into physical quantities by using this option.
