### ISSUE TITLE
[log2ubx] OBSERVER_SIZE is too small for large size of ubx messages

### ISSUE THREAD

**Issue by HirakuTOIDA** [fenrir-naru/ninja-scan-light#7]
When I convert log files generated by ninja-scan-compatible logger using NEO-M8T, log2ubx report that the log files contain a large amount of bad packets.
Judging from missing messages of the generated ubx files, log2ubx can not handle large ublox packet (e.g. RXM-RAWX) properly due to small size of OBSERVER_SIZE.
After increasing OBSERVER_SIZE to PAGE_SIZE * 64 (=2048), I confirm that all the massages including RXM-RAWX are successfully converted, at least for my case.
Although this may not affect the log files generated by ninja-scan-light, it is better to increase OBSERVER_SIZE for better compatibility with all the u-blox modules.

**Comment by fenrir-naru** [comment]
I agree with your proposal. I've merged your PR. Thanks. #8
